### ISSUE TITLE
Build fails with carthage --use-xcframeworks flag

### ISSUE THREAD

**Issue by bud-burroughs** [PromiseKit/Foundation#27]
Carthage now recommends using the --use-xcframeworks flag, and it's required for Macs with Apple Silicon. However, Foundation fails to build with this flag set.
Last few lines of build log:
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/PMKFoundation.h"
        ^
/Users/wburro0009e/Documents/Development/sec-client-iOS/Carthage/Checkouts/Foundation/Sources/PMKFoundation.h:1:9: note: in file included from /Users/wburro0009e/Documents/Development/sec-client-iOS/Carthage/Checkouts/Foundation/Sources/PMKFoundation.h:1:
#import "NSNotificationCenter+AnyPromise.h"
        ^
/Users/wburro0009e/Documents/Development/sec-client-iOS/Carthage/Checkouts/Foundation/Sources/NSNotificationCenter+AnyPromise.h:2:9: error: 'PromiseKit/AnyPromise.h' file not found
#import <PromiseKit/AnyPromise.h>
        ^
<unknown>:0: error: could not build Objective-C module 'PMKFoundation'

**Comment by ajelden** [comment]
This issue is holding up at least two teams at our company. We are pursuing a workaround, but would also like to know if any contributors are working on a solution.

**Comment by mxcl** [comment]
For me this works now, reopen if you have issues.
