### ISSUE TITLE
Won't compile with the latest PromiseKit because of difference in SPM Package file

### ISSUE THREAD

**Issue by zeusent** [PromiseKit/Foundation#30]
Because the latest PromiseKit updated it's SPM manifest for Swift 5.3 and added a minimum requirement of iOS 9 this package won't compile anymore. An error is thrown:

> The package product 'PromiseKit' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0

Can we have this fixed?

**Comment by mxcl** [comment]
Sponsorship or PR welcome

**Comment by zeusent** [comment]
Should be here: https://github.com/PromiseKit/Foundation/pull/31

**Comment by zeusent** [comment]
I'm not sure if I was supposed to do this or not, but can you make a new release for this? A new version tag should be made  guess 🙄

**Comment by mxcl** [comment]
Yeah I'm on it, if you check the various PRs and commit history I am busy with CI/CD related tasks to get this out. Thanks for the PR

**Comment by mxcl** [comment]
v3.4.0 released
