### ISSUE TITLE
Naming conflict with Alamofire for URLRequestConvertible

### ISSUE THREAD

**Issue by swoolcock** [PromiseKit/Foundation#5]
The latest version of PromiseKit/Foundation has a naming conflict with the `URLRequestConvertible` protocol in Alamofire, which has existed since 2014.

https://github.com/Alamofire/Alamofire/commit/5b94f2a2f1a368a63db2e692b9004a236560c0f3

While we can certainly go through and fully qualify (or typealias) anything that uses it, it may not be a good idea to force PromiseKit users to change non-PromiseKit code as part of a migration process.

**Comment by mxcl** [comment]
Can you provide a concrete example of a situation this has effected?

I can't off hand imagine anything that would cause this to be a problem since it is unlikely anyone is importing both frameworks into a file where for some reason they are also having to explicitly use the `URLRequestConvertible` symbol.

**Comment by swoolcock** [comment]
We follow this router pattern: https://grokswift.com/router/

However we also import PromiseKit in the same file.  On further investigation it seems we can actually remove that import anyway, so it's not a big deal.

It's an unfortunate problem with Swift's lack of explicit namespaces.  If you feel that this is a non-issue, please close.  I figured it would be good to give a heads up anyway.

**Comment by mxcl** [comment]
I'm cool with changing it, just wanted a concrete example to prove it is worth potentially breaking people's code (not much is likely IMO) and also so I know for future reference what sort of things to avoid.

I guess you must have functions that take `URLRequestConvertible`?

**Comment by swoolcock** [comment]
The router enum pattern lets you do something like the following:

`Alamofire.request(Router.getCustomers).responseJSON { response in ... }`

Where `Router` is an enum that conforms to `URLRequestConvertible`.  Alamofire allows you to pass in a `URLRequestConvertible` so that you can easily preconfigure your request.

**Comment by joserafaelrocha** [comment]
I'm facing this too :(

**Comment by mxcl** [comment]
There are many ways to deal with this:

* Reduce the scope of import from PromiseKit: `import class PromiseKit.Promise`
* Qualify `URLRequestConvertible`: `func foo(_ bar: Alamofire.URLRequestConvertible)`
* Use a `typealias` under your imports: `typealias URLRequestConvertible = Alamofire.URLRequestConvertible`
* Specify PromiseKit to not import the Foundation extensions: `pod PromiseKit/CorePromise`

**Comment by garyhooper** [comment]
Same problem here. And I'm using PromiseKit to check the results of my AlamoFire router.

**Comment by blackgold9** [comment]
Running into this myself

**Comment by momentummobiletest** [comment]
I created a Disambiguation typealias to solve this in 2 different files:

```swift
import PromiseKit
import Foundation

typealias PromiseKitRequestConvertible = URLRequestConvertible
```
```swift
import Foundation
import Alamofire

typealias AlamofireRequestConvertible = URLRequestConvertible

````
